/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /tmp/airplane.glb -t -r /home/nbuck/aircraft-leasing-poc/frontend/public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    body_1: THREE.Mesh
    body_2: THREE.Mesh
    body_3: THREE.Mesh
    body_4: THREE.Mesh
    body_5: THREE.Mesh
    body_6: THREE.Mesh
    body_7: THREE.Mesh
    body_8: THREE.Mesh
    body_9: THREE.Mesh
    body_10: THREE.Mesh
    front_gear_1: THREE.Mesh
    front_gear_2: THREE.Mesh
    lights_anti_collision_red_volume: THREE.Mesh
    lights_position_green_volume: THREE.Mesh
    lights_position_red_volume: THREE.Mesh
    lights_position_white_volume: THREE.Mesh
    lights_taxi_white_volume: THREE.Mesh
    propeller_left_inner_1: THREE.Mesh
    propeller_left_inner_2: THREE.Mesh
    propeller_left_inner_blur: THREE.Mesh
    propeller_left_outer_1: THREE.Mesh
    propeller_left_outer_2: THREE.Mesh
    propeller_left_outer_blur: THREE.Mesh
    propeller_right_inner_1: THREE.Mesh
    propeller_right_inner_2: THREE.Mesh
    propeller_right_inner_blur: THREE.Mesh
    propeller_right_outer_1: THREE.Mesh
    propeller_right_outer_2: THREE.Mesh
    propeller_right_outer_blur: THREE.Mesh
    rear_gears_1: THREE.Mesh
    rear_gears_2: THREE.Mesh
  }
  materials: {
    body_0: THREE.MeshStandardMaterial
    body_1: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    lights_anti_collision_red: THREE.MeshStandardMaterial
    lights_position_red: THREE.MeshStandardMaterial
    lights_position_green: THREE.MeshStandardMaterial
    lights_position_white: THREE.MeshStandardMaterial
    lights_taxi_white: THREE.MeshStandardMaterial
    mapbox_logo_white: THREE.MeshStandardMaterial
    mapbox_logo_black: THREE.MeshStandardMaterial
    rubber: THREE.MeshStandardMaterial
    lights_anti_collision_red_volume: THREE.MeshStandardMaterial
    lights_position_green_volume: THREE.MeshStandardMaterial
    lights_position_red_volume: THREE.MeshStandardMaterial
    lights_position_white_volume: THREE.MeshStandardMaterial
    lights_taxi_white_volume: THREE.MeshStandardMaterial
    plastic: THREE.MeshStandardMaterial
    propeller_blur: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/../../../../../tmp/airplane.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body_1.geometry} material={materials.body_0} />
      <mesh geometry={nodes.body_2.geometry} material={materials.body_1} />
      <mesh geometry={nodes.body_3.geometry} material={materials.glass} />
      <mesh geometry={nodes.body_4.geometry} material={materials.lights_anti_collision_red} />
      <mesh geometry={nodes.body_5.geometry} material={materials.lights_position_red} />
      <mesh geometry={nodes.body_6.geometry} material={materials.lights_position_green} />
      <mesh geometry={nodes.body_7.geometry} material={materials.lights_position_white} />
      <mesh geometry={nodes.body_8.geometry} material={materials.lights_taxi_white} />
      <mesh geometry={nodes.body_9.geometry} material={materials.mapbox_logo_white} />
      <mesh geometry={nodes.body_10.geometry} material={materials.mapbox_logo_black} />
      <group position={[-9.062, 2.556, -0.008]} scale={0.085}>
        <mesh geometry={nodes.front_gear_1.geometry} material={materials.body_0} />
        <mesh geometry={nodes.front_gear_2.geometry} material={materials.rubber} />
      </group>
      <mesh geometry={nodes.lights_anti_collision_red_volume.geometry} material={materials.lights_anti_collision_red_volume} />
      <mesh geometry={nodes.lights_position_green_volume.geometry} material={materials.lights_position_green_volume} />
      <mesh geometry={nodes.lights_position_red_volume.geometry} material={materials.lights_position_red_volume} />
      <mesh geometry={nodes.lights_position_white_volume.geometry} material={materials.lights_position_white_volume} />
      <mesh geometry={nodes.lights_taxi_white_volume.geometry} material={materials.lights_taxi_white_volume} />
      <group position={[-1.142, 3.089, 4.959]} rotation={[0, -1.571, 0]} scale={0.578}>
        <mesh geometry={nodes.propeller_left_inner_1.geometry} material={materials.body_0} />
        <mesh geometry={nodes.propeller_left_inner_2.geometry} material={materials.plastic} />
      </group>
      <mesh geometry={nodes.propeller_left_inner_blur.geometry} material={materials.propeller_blur} position={[-1.405, 3.089, 4.959]} rotation={[0, -1.571, 0]} />
      <group position={[0.041, 3.289, 10.395]} rotation={[0, -1.571, 0]} scale={0.578}>
        <mesh geometry={nodes.propeller_left_outer_1.geometry} material={materials.body_0} />
        <mesh geometry={nodes.propeller_left_outer_2.geometry} material={materials.plastic} />
      </group>
      <mesh geometry={nodes.propeller_left_outer_blur.geometry} material={materials.propeller_blur} position={[-0.221, 3.289, 10.395]} rotation={[0, -1.571, 0]} />
      <group position={[-1.142, 3.089, -4.959]} rotation={[0, -1.571, 0]} scale={0.578}>
        <mesh geometry={nodes.propeller_right_inner_1.geometry} material={materials.body_0} />
        <mesh geometry={nodes.propeller_right_inner_2.geometry} material={materials.plastic} />
      </group>
      <mesh geometry={nodes.propeller_right_inner_blur.geometry} material={materials.propeller_blur} position={[-1.405, 3.089, -4.959]} rotation={[0, -1.571, 0]} />
      <group position={[0.041, 3.289, -10.395]} rotation={[0, -1.571, 0]} scale={0.578}>
        <mesh geometry={nodes.propeller_right_outer_1.geometry} material={materials.body_0} />
        <mesh geometry={nodes.propeller_right_outer_2.geometry} material={materials.plastic} />
      </group>
      <mesh geometry={nodes.propeller_right_outer_blur.geometry} material={materials.propeller_blur} position={[-0.221, 3.289, -10.395]} rotation={[0, -1.571, 0]} />
      <group position={[4.602, 2.602, 0]}>
        <mesh geometry={nodes.rear_gears_1.geometry} material={materials.body_0} />
        <mesh geometry={nodes.rear_gears_2.geometry} material={materials.rubber} />
      </group>
    </group>
  )
}

useGLTF.preload('/../../../../../tmp/airplane.glb')
